server:
  port: 8072
eureka:
  instance:
    #    register IP address of the service rather than the server hostname
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://default:8070/eureka/}
spring:
  zipkin:
    baseUrl: ${ZIPKIN_SERVER}
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"